### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by 1x6** [nab0rs/NitroTypeBots#1]
[deleted]

**Comment by sslprograms** [comment]
> [cc10e88](https://github.com/sslprograms/NitroTypeBots/commit/cc10e884a87d462b24c6de0e0117556c929c8acc)
> its all right here lol
> ![image](https://user-images.githubusercontent.com/44981148/119541648-90f25500-bd86-11eb-9535-e3cc21deb1b8.png)

well its alright now. i think its patched.
